//
//  TransferStatus.h
//  objective-curl
//
//  Copyright 2010 Nick Jensen <http://goto11.net>
//

typedef enum {
	CURL_TRANSFER_STATUS_QUEUED = 1,
	CURL_TRANSFER_STATUS_CONNECTING,
	CURL_TRANSFER_STATUS_CONNECTED,
	CURL_TRANSFER_STATUS_UPLOADING,
	CURL_TRANSFER_STATUS_COMPLETE,
	CURL_TRANSFER_STATUS_CANCELLED,
	CURL_TRANSFER_STATUS_LOGIN_DENIED,
	CURL_TRANSFER_STATUS_FAILED
} CurlTransferStatus;
